- hosts: all
  roles:
    - Basic_Configuration

- hosts: Master
  vars_prompt:
          - name: network
            prompt: "Enter The Network ID for your cluster network"
            private: no        
          
          - name: cidr
            prompt: "Enter The Cidr for your cluster"  
            private: no
  roles: 
    - Master
 
- hosts: slave
  roles:
    - Worker

- hosts: Master
  vars_prompt:
        - name: deployment_name
          prompt: "Enter your preferred Deployment Name"
          private: no

        - name: image_name
          prompt: "Enter your preferred docker image name"
          private: no

        - name: container_name
          prompt: "Enter your preferred container name"
          private: no          

        - name: port
          prompt: "Enter port you want to expose"
          private: no

        - name: expose_type
          prompt: "Enter the expose type you want to use"
          private: no
  roles:
    - deployment
      



