apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: "{{ deployment_name }}"
  name: "{{ deployment_name }}"
spec:
  ports:
  - port: {{ port | int }}
    protocol: TCP
    targetPort: {{ port | int }}
  selector:
    app: "{{ deployment_name }}"
  type: "{{ expose_type }}"
